#!/usr/bin/env bash
# Run osquery to list listening sockets with process info

osqueryi --list --separator ',' <<'EOF' | cut -c 1-300 | column -t -s ',' | sed '1d' | rg -v '(rapportd|node.mojom.NodeService|wormhole)'
SELECT s.pid, s.local_port, p.cmdline, p.cwd
FROM process_open_sockets AS s
INNER JOIN processes AS p
ON s.pid = p.pid
WHERE s.state = 'LISTEN'
ORDER BY p.cmdline;
EOF

